services:
  bk-demo:
    build: .
    container_name: bk-demo
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3011
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.bk-demo.entrypoints=websecure"
      - "traefik.http.routers.bk-demo.rule=Host(`bk-demo.cyberworldbuilders.dev`)"
      - "traefik.http.routers.bk-demo.tls=true"
      - "traefik.http.routers.bk-demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.bk-demo.loadbalancer.server.port=3011"
    restart: unless-stopped

networks:
  traefik-net:
    external: true 